---

# Less commonly application variables -
# things the user is less-like to want to change (but can).
# This is here to avoid clutter in 'defaults/main.yaml'

# The application Pod Security Policy (PSP)
fp_sa_psp: im-core-unrestricted

# Application CPU and Memory requests and limits.
# Requests are required but limits are not.
# Set limit to blank ('') to avoid a limit.
fp_cpu_request: 1
fp_cpu_limit: 2
fp_mem_request: 4Gi
fp_mem_limit: 4Gi

# The player container user-ID
fp_player_uid: 1000

# How long to hold-on to the player Pod
# (keep alive for post-run debug)
fp_keep_alive_seconds: 0

# General variables

wait_timeout: 120
pod_ready_timeout: 600
