---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# The controller playbook to run.
fc_play: SetMe

# The namespace that is expected to exist.
fc_namespace: fragmentor
# The name of the 'pgcopy' volume (that we can mount).
# It's also mounted into the database (at `/pgcopy`).
# This PVC must exist and must be of the type `ReadWriteMany`.
fc_pgcopy_pvc_name: pgcopy

# Details of the fragmentation controller container image
fc_image_name: alanbchristie/fragmentor-controller
fc_image_tag: 'latest'

# The 'work' volume.
# Shared with all the workflow containers that get launched.
fc_work_volume_storageclass: efs
fc_work_volume_size_g: 1

# Read the content of the parameters file.
# This wil e injected into the parameter config map.
fc_parameter_file: parameters.yaml

# The pull-secret
fc_pull_secret: '00000000'

# AWS credentials (for bucket access).
# Expected in the environment.
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
